<!DOCTYPE html><!---cabecalho---->
<html lang="pt-br">
<head>
	<meta charset="utf-8"/>
	<title>Estoque</title>	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<style>
		.content {
			margin-top:30px;
		}
	</style>

</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		<a class="navbar-brand" href="#">Estoque</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="<?php=HOME; ?>">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/fazerPedido.php">Fazer pedido de Estoque</a>
			</ul>
			<form class="form-inline mt-2 mt-md-0">
				</form>
		</div>
	</nav>
<div class="container content">